---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hackathon
  labels:
    app: hackathon
spec:
  selector:
    matchLabels:
      app: hackathon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
      - name: hackathon
        image: daniel36/hackathon-ponto-eletronico:latest
        args:
        - "-text=hackathon"
        ports:
        - containerPort: 5678
          protocol: TCP
        resources:
          requests:
            cpu: 200m