---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hackathon
  labels:
    app: hackathon
spec:
  selector:
    matchLabels:
      app: hackathon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
      - name: hackathon
        image: daniel36/hackathon-ponto-eletronico:latest
        args:
        - "-text=hackathon"
        ports:
        - containerPort: 5678
          protocol: TCP
        resources:
          requests:
            cpu: 200m

        env:
          - name: MONGO_HOST
            value: mongo-db
          - name: MONGO_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config-map
                key: mongo-username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password

          - name: TOKEN_SECURITY
            valueFrom:
              secretKeyRef:
                name: token-security
                key: TOKEN_SECURITY
          - name: EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: email-password
                key: EMAIL_PASSWORD