apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackathon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielcorreaa/kind-kong.git
    targetRevision: HEAD
    path: apps/hackathon
  destination:
    server: https://kubernetes.default.svc
    namespace: hackathon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true